import os
from dotenv import load_dotenv, find_dotenv

from utilities.encryption import decrypt
from settings.constant import (
  ENV_NAME,
  PATH_CACHE_DIRECTORY,
  PATH_FILE_DTCC_JAR,
  PATH_FILE_KEY_MASTER,
  PATH_FILE_KEY_BITBUCKET,
)

__all__ = [
  "TALEND_URL",
  "TALEND_USER",
  "TALEND_PASSWORD",
  "METASERVLET_CALLER",
  "BITBUCKET_DATA_SOURCE_TOKEN",
  "BITBUCKET_DATA_SOURCE_BRANCH",
  "BITBUCKET_DATA_SOURCE_URL",
  "BITBUCKET_DATA_SOURCE_DIRECTORY",
  "TALEND_SCRAPPER_SSO_FLAG",
  "TALEND_SCRAPPER_SSO_URL",
  "TALEND_SCRAPPER_SSO_USER",
  "TALEND_SCRAPPER_SSO_DOMAIN",
  "TALEND_SCRAPPER_SSO_PATH_COMMAND",
  "TALEND_SCRAPPER_SSO_CONF_INI",
  "MANIFEST_PATH",
  "LOG_LEVEL",
  "LOG_NAME",
]

load_dotenv(dotenv_path=os.path.join(PATH_CACHE_DIRECTORY, ENV_NAME))

TALEND_URL = os.environ.get('TALEND_URL')
TALEND_USER = os.environ.get('TALEND_USER')
if os.environ.get("IS_PASSWORD_ENCRYPTED")=="1":
  TALEND_PASSWORD = decrypt(
    os.environ.get('TALEND_PASSWORD'),
    PATH_FILE_KEY_MASTER,
    PATH_FILE_DTCC_JAR,
  )
else:
  TALEND_PASSWORD = os.environ.get('TALEND_PASSWORD')

METASERVLET_CALLER = os.environ.get('METASERVLET_CALLER')

BITBUCKET_DATA_SOURCE_TOKEN = decrypt(
    os.environ.get('BITBUCKET_DATA_SOURCE_TOKEN'),
    PATH_FILE_KEY_BITBUCKET,
    PATH_FILE_DTCC_JAR,
)
BITBUCKET_DATA_SOURCE_BRANCH = os.environ.get('BITBUCKET_DATA_SOURCE_BRANCH')
BITBUCKET_DATA_SOURCE_URL = os.environ.get('BITBUCKET_DATA_SOURCE_URL')

TALEND_SCRAPPER_SSO_FLAG = os.environ.get('TALEND_SCRAPPER_SSO_FLAG')
TALEND_SCRAPPER_SSO_URL = os.environ.get('TALEND_SCRAPPER_SSO_URL')
TALEND_SCRAPPER_SSO_USER = os.environ.get('TALEND_SCRAPPER_SSO_USER')

# one password if the SSO login.
TALEND_SCRAPPER_SSO_DOMAIN = os.environ.get('TALEND_SCRAPPER_SSO_DOMAIN')
TALEND_SCRAPPER_SSO_PATH_COMMAND = os.environ.get('TALEND_SCRAPPER_SSO_PATH_COMMAND')
TALEND_SCRAPPER_SSO_CONF_INI = os.environ.get('TALEND_SCRAPPER_SSO_CONF_INI')

MANIFEST_PATH = os.environ.get('MANIFEST_PATH')
LOG_LEVEL = os.environ.get('LOG_LEVEL', "INFO")
LOG_NAME = os.environ.get('LOG_NAME', "command.log")
